// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Allow TypeScript to recognize the global `process` without requiring @types/node here.
declare const process: any;

import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});